name: Run Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-biome:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Biome
      run: pnpm add -D -E @biomejs/biome

    - name: Run Biome
      run: pnpm exec biome check
